---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-test-dep
  labels:
    app: grpc-test-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: grpc-test-dep
  template:
    metadata:
      labels:
        app: grpc-test-dep
    spec:
      containers:
        - name: test-container
          image: test-server
          ports:
            - containerPort: 50051
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: grpc-test-dep
  ports:
    - port: 8000
      targetPort: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik
  namespace: default
spec:
  gatewayClassName: traefik

  listeners:
    - name: grpc
      protocol: HTTP
      port: 8000

      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: echo
  namespace: default
spec:
  parentRefs:
    - name: traefik
      sectionName: grpc
      kind: Gateway

  hostnames:
    - echo.test

  rules:
    - backendRefs:
        - name: my-service
          namespace: default
          port: 8000
